# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Gobierto · Plataforma de Gobierto Abierto open source"
description: Gobierto ofrece metodología y herramientas open source para desplegar iniciativas de gobierno abierto. Transparencia, Participación, Rendición de Cuentas y Comunicación Ciudadana.
baseurl: "" # the subpath of your site, e.g. /blog

# default permalink for blog posts
permalink: /blog/:year:month:day-:title.html

collections:
  static_pages:
    output: true
    permalink: /pages/:path/
  newsletters:
    output: true
    permalink: /newsletters/:title.html
  widgets:
    output: true
    permalink: /widgets/:title/
  charts:
    output: true
    permalink: /charts/:path/
  category:
    output: true
    permalink: /temas/:title/


# urls for sections/pages
url_producto_presupuestos_visualizacion: "visualizacion_presupuestos_municipales"
url_producto_presupuestos_consultas: "presupuestos_participativos_consultas"
url_producto_presupuestos_historias:
url_producto_presupuestos_inteligencia:

# The configuration entry `url` is generated in plugins/site_url_generator.rb depending on the environment variable
production_url: "http://gobierto.es"
staging_url: ""
development_url: "http://localhost:4000"

twitter_username: "@gobierto"
twitter_hashtag_for_social_share: '#gobierto'

# Build settings
markdown: kramdown
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'Rakefile', '_config.yml', 'bin', '.git', '.asset-cache']

plugins: [jekyll-assets]

# jekyll-press:
#   exclude: '*.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
#   js_options: {}      # js minifier options
#   css_options: {}     # css minifier options
#   html_options: {}    # html minifier options

# Plugin: jekyll-assets
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascript
    - _assets/images/v1
    - _assets/images/v2
    - _assets/stylesheets
  # gzip: [ text/css, application/javascript ]
  digest: false
  # compressors:
  #   uglifier:
  #     harmony: true
  #     compress:
  #       unused: false

timezone: Europe/Madrid
